language: csharp
mono: none
sudo: required
dotnet: 2.2
solution: src/Loggy.sln
script:
 - cd src
 - dotnet restore
 - dotnet build -c Release
global:
 - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
 - DOTNET_CLI_TELEMETRY_OPTOUT=1